version: '2'
services:
  tensorflow:
    image: docker-tensorflow-aarch64/tensorflow
    build: ./tensorflow
  sensor-import:
    privileged: true
    image: docker-tensorflow-aarch64/sensor
    build: ./sensor-import
